# -*- coding: utf-8 -*-
"""Heartbeat anomaly

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_14KlSSbApTHhMY4TnL1H7Zb2FObt0on
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install wfdb rank_bm25 FlagEmbedding sentence-transformers

print('Attempting to fix potential library version conflicts...')
!pip uninstall -y transformers FlagEmbedding sentence-transformers tokenizers
!pip install transformers==4.32.0
!pip install FlagEmbedding sentence-transformers

from google.colab import userdata
hf_token = userdata.get('HF_TOKEN')
from huggingface_hub import login
login(hf_token)

from transformers import pipeline
import torch

# Determine the device to use
device = 0 if torch.cuda.is_available() else -1 # -1 for CPU

llm = pipeline(
    "text-generation",
    model="mistralai/Mistral-7B-Instruct-v0.2",
    device=device,
    max_new_tokens=300,
)

def ask_llm(prompt):
    # Send a prompt to the LLM and return only the new response text
    result = llm(prompt)
    full_text = result[0]['generated_text']
    response_only = full_text[len(prompt):].strip()
    return response_only

import os, zipfile, glob, random, re
import numpy as np
import pandas as pd
from tqdm import tqdm
import matplotlib.pyplot as plt
import wfdb
from scipy.signal import resample
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity
from rank_bm25 import BM25Okapi
from sentence_transformers import CrossEncoder

ZIP_PATH = "/content/drive/MyDrive/AI Capstone (1)/mit-bih-arrhythmia-database-1.0.0.zip"
OUT_DIR  = "/content/mitbih"
BASE_DIR = os.path.join(OUT_DIR, "mit-bih-arrhythmia-database-1.0.0")

TARGET_FS = 72
WINDOW_SEC = 0.8
N_SAMPLES = int(TARGET_FS * WINDOW_SEC)
LABEL_MAP = {"N": "Normal", "V": "PVC"}
MAX_EACH = 500
TOP_K = 5  # chunks to retrieve before reranking
TOP_RERANK = 2  # chunks to keep after reranking
random.seed(42)
np.random.seed(42)

if not os.path.exists(BASE_DIR):
    os.makedirs(OUT_DIR, exist_ok=True)
    with zipfile.ZipFile(ZIP_PATH) as z:
        z.extractall(OUT_DIR)

records = [
    os.path.splitext(os.path.basename(f))[0]
    for f in sorted(glob.glob(os.path.join(BASE_DIR, "*.hea")))
]

print(f"records found: {len(records)}")


def extract_features(x, decimals=2):
    return {
        "mean": float(np.mean(x)),
        "variance": float(np.var(x)),
        "fft_mean_magnitude": float(np.mean(np.abs(np.fft.rfft(x)))),
        "signal_text": ", ".join(f"{v:.{decimals}f}" for v in x),
    }


rows = []
counts = {"Normal": 0, "PVC": 0}

for rec_name in tqdm(records):
    if all(c >= MAX_EACH for c in counts.values()):
        break
    try:
        record = wfdb.rdrecord(os.path.join(BASE_DIR, rec_name))
        ann = wfdb.rdann(os.path.join(BASE_DIR, rec_name), "atr")
    except Exception:
        continue

    fs = int(record.fs)
    lead_idx = record.sig_name.index("MLII") if "MLII" in record.sig_name else 0
    signal = record.p_signal[:, lead_idx]
    half = int((WINDOW_SEC / 2) * fs)

    for sample_idx, sym in zip(ann.sample, ann.symbol):
        label = LABEL_MAP.get(sym)
        if not label or counts[label] >= MAX_EACH:
            continue

        start, end = sample_idx - half, sample_idx + half
        if start < 0 or end > len(signal):
            continue

        # Resample to exact N_SAMPLES instead of integer-ratio approximation
        window = resample(signal[start:end], N_SAMPLES)
        rows.append({"label": label, "record": rec_name,
                     "beat_sample": sample_idx, **extract_features(window)})
        counts[label] += 1

print(f"Collected: {counts}")
df = pd.DataFrame(rows)
df.to_csv("/content/drive/MyDrive/AI Capstone (1)/ecg_nv_72hz_llm_ready.csv", index=False)
print("Saved.")

os.makedirs("/content/drive/MyDrive/AI Capstone (1)/Docs", exist_ok=True)
Docs = [
    "Electrocardiogram (ECG) signals measure the electrical activity of the heart over time. The waveform reflects the depolarization and repolarization of heart muscle during each heartbeat. ",
    "A typical ECG waveform contains several components including the P wave, QRS complex, and T wave. The QRS complex represents ventricular contraction and is usually sharp and narrow in normal heartbeats.",
    "Normal heartbeats typically show consistent waveform shapes and regular timing between beats. The electrical signal pattern remains stable across multiple heart cycles.",
    "Premature Ventricular Contractions (PVCs) occur when an electrical impulse originates in the ventricles instead of the normal conduction pathway. These beats often appear earlier than expected.",
    "PVC beats often produce wider or distorted waveform shapes compared to normal beats. The abnormal electrical origin can lead to irregular signal patterns.",
    "In ECG signals, normal heartbeats usually maintain a consistent morphology across time. Abnormal beats may show sudden changes in amplitude or waveform shape.",
    "Signal variance can increase when abnormal heartbeats occur. PVC events often introduce irregular waveform features that differ from surrounding normal beats.",
    "Noise in ECG signals can come from muscle movement, electrode displacement, or electrical interference. These artifacts should be distinguished from true cardiac abnormalities.",
    "The timing and shape of ECG waveforms provide important information about cardiac function. Deviations from expected patterns may indicate arrhythmias or abnormal beats.",
    "ECG analysis often involves identifying characteristic waveform shapes and comparing them with known patterns for normal and abnormal heart activity."
    ]
for i, text in enumerate(Docs, start=1):
    filepath = f"/content/drive/MyDrive/AI Capstone (1)/Docs/Doc{i}.txt"
    with open(filepath, "w") as file:
        file.write(text)

# FIX 2: Demos list defined and written to disk (was never saved in original)
os.makedirs("/content/drive/MyDrive/AI Capstone (1)/Demos", exist_ok=True)
Demos = [
    """TASK: Heartbeat anomaly detection (ECG)
    QUESTION:
    Classify the heartbeat as Normal or PVC.
    INPUT:
    Signal_summary: The waveform is regular and consistent across the window with no obvious distortion.
    Features: mean=0.03, variance=0.01, fft_mean_magnitude=0.22
    Context: ECG sampled at 72Hz, window ~0.8s, lead=MLII
    REASONING:
    Step 1: Low variance suggests stable morphology without abrupt abnormal deviations.
    Step 2: Regular shape is typical of normal beats rather than ventricular-origin abnormalities.
    Step 3: No strong indicators of abnormal morphology are described.
    ANSWER:
    LABEL: Normal
    CONFIDENCE: 78""",

    """TASK: Heartbeat anomaly detection (ECG)
    QUESTION:
    Classify the heartbeat as Normal or PVC.
    INPUT:
    Signal_summary: The waveform shows an abrupt shape change and appears less regular than surrounding beats.
    Features: mean=0.05, variance=0.04, fft_mean_magnitude=0.35
    Context: ECG sampled at 72Hz, window ~0.8s, lead=MLII
    REASONING:
    Step 1: Higher variance indicates irregular changes in the signal.
    Step 2: Sudden morphology change is consistent with abnormal ventricular activity.
    Step 3: This pattern matches typical PVC descriptions more than normal beats.
    ANSWER:
    LABEL: PVC
    CONFIDENCE: 82""",

    """TASK: Heartbeat anomaly detection (ECG)
    QUESTION:
    Classify the heartbeat as Normal or PVC.
    INPUT:
    Signal_summary: Peaks and troughs follow a stable pattern and the overall signal variation is small.
    Features: mean=0.02, variance=0.01, fft_mean_magnitude=0.20
    Context: ECG sampled at 72Hz, window ~0.8s, lead=MLII
    REASONING:
    Step 1: Small variance suggests the signal is not showing abnormal irregularity.
    Step 2: Stable morphology aligns with typical normal heartbeat patterns.
    Step 3: Nothing indicates a distorted or abnormal beat shape.
    ANSWER:
    LABEL: Normal
    CONFIDENCE: 76""",

    """TASK: Heartbeat anomaly detection (ECG)
    QUESTION:
    Classify the heartbeat as Normal or PVC.
    INPUT:
    Signal_summary: The signal looks distorted with an unusual broad-looking shape compared to typical beats.
    Features: mean=0.06, variance=0.05, fft_mean_magnitude=0.38
    Context: ECG sampled at 72Hz, window ~0.8s, lead=MLII
    REASONING:
    Step 1: Elevated variance suggests abnormal waveform variability.
    Step 2: Distorted morphology is commonly associated with PVC beats.
    Step 3: The described pattern is more consistent with PVC than normal.
    ANSWER:
    LABEL: PVC
    CONFIDENCE: 84""",

    """TASK: Heartbeat anomaly detection (ECG)

    QUESTION:
    Classify the heartbeat as Normal or PVC.

    INPUT:
    Signal_summary: The waveform appears smooth and repeatable with consistent amplitude.
    Features: mean=0.04, variance=0.01, fft_mean_magnitude=0.23
    Context: ECG sampled at 72Hz, window ~0.8s, lead=MLII

    REASONING:
    Step 1: Consistent amplitude and low variance indicate stable behavior.
    Step 2: Smooth, repeatable morphology matches normal beat characteristics.
    Step 3: No abnormal spike or irregular distortion is described.

    ANSWER:
    LABEL: Normal
    CONFIDENCE: 79""",

    """TASK: Heartbeat anomaly detection (ECG)

    QUESTION:
    Classify the heartbeat as Normal or PVC.

    INPUT:
    Signal_summary: The window contains an unusual spike and the waveform shape differs noticeably from typical beats.
    Features: mean=0.07, variance=0.04, fft_mean_magnitude=0.36
    Context: ECG sampled at 72Hz, window ~0.8s, lead=MLII

    REASONING:
    Step 1: Noticeable shape difference suggests an abnormal beat morphology.
    Step 2: The irregular spike and deviation align with PVC descriptions.
    Step 3: The evidence points more strongly to PVC than a normal beat.

    ANSWER:
    LABEL: PVC
    CONFIDENCE: 80""",

    """TASK: Heartbeat anomaly detection (ECG)

    QUESTION:
    Classify the heartbeat as Normal or PVC.

    INPUT:
    Signal_summary: The signal pattern remains consistent throughout the window with no sudden changes.
    Features: mean=0.01, variance=0.01, fft_mean_magnitude=0.19
    Context: ECG sampled at 72Hz, window ~0.8s, lead=MLII

    REASONING:
    Step 1: No sudden changes suggests the beat morphology is stable.
    Step 2: Stable morphology is typical for normal beats.
    Step 3: There are no described indicators of abnormal ventricular-origin activity.

    ANSWER:
    LABEL: Normal
    CONFIDENCE: 74""",

    """TASK: Heartbeat anomaly detection (ECG)

    QUESTION:
    Classify the heartbeat as Normal or PVC.

    INPUT:
    Signal_summary: The waveform appears irregular with larger fluctuations than expected in a normal beat.
    Features: mean=0.05, variance=0.05, fft_mean_magnitude=0.40
    Context: ECG sampled at 72Hz, window ~0.8s, lead=MLII

    REASONING:
    Step 1: Large fluctuations increase variance and suggest abnormal behavior.
    Step 2: Irregular morphology is consistent with PVC characteristics.
    Step 3: The described irregularity is more likely PVC than normal.

    ANSWER:
    LABEL: PVC
    CONFIDENCE: 85""",

    """TASK: Heartbeat anomaly detection (ECG)

    QUESTION:
    Classify the heartbeat as Normal or PVC.

    INPUT:
    Signal_summary: The waveform has a consistent pattern and the signal does not look distorted.
    Features: mean=0.03, variance=0.02, fft_mean_magnitude=0.24
    Context: ECG sampled at 72Hz, window ~0.8s, lead=MLII

    REASONING:
    Step 1: Moderate-low variance still supports stable morphology.
    Step 2: No distortion suggests normal beat structure.
    Step 3: Lacking abnormal morphology indicators, normal is most likely.

    ANSWER:
    LABEL: Normal
    CONFIDENCE: 73""",

    """TASK: Heartbeat anomaly detection (ECG)

    QUESTION:
    Classify the heartbeat as Normal or PVC.

    INPUT:
    Signal_summary: The signal shows a sudden abnormal deviation and does not match the expected normal pattern.
    Features: mean=0.06, variance=0.04, fft_mean_magnitude=0.34
    Context: ECG sampled at 72Hz, window ~0.8s, lead=MLII

    REASONING:
    Step 1: Sudden deviation indicates abnormal morphology within the window.
    Step 2: Not matching the expected pattern suggests an abnormal beat type.
    Step 3: This aligns more with PVC than normal.

    ANSWER:
    LABEL: PVC
    CONFIDENCE: 81""",

    """TASK: Heartbeat anomaly detection (ECG)

    QUESTION:
    Classify the heartbeat as Normal or PVC.

    INPUT:
    Signal_summary: The beat shape is consistent and the amplitude variations are small across the segment.
    Features: mean=0.02, variance=0.01, fft_mean_magnitude=0.21
    Context: ECG sampled at 72Hz, window ~0.8s, lead=MLII

    REASONING:
    Step 1: Small amplitude variation implies stable rhythm behavior.
    Step 2: Consistent beat shape matches normal morphology.
    Step 3: No clear abnormal pattern is present.

    ANSWER:
    LABEL: Normal
    CONFIDENCE: 77""",

    """TASK: Heartbeat anomaly detection (ECG)

    QUESTION:
    Classify the heartbeat as Normal or PVC.

    INPUT:
    Signal_summary: The waveform looks atypical and irregular, suggesting an abnormal beat morphology.
    Features: mean=0.06, variance=0.06, fft_mean_magnitude=0.42
    Context: ECG sampled at 72Hz, window ~0.8s, lead=MLII

    REASONING:
    Step 1: High variance suggests strong irregular changes in the waveform.
    Step 2: Atypical morphology is consistent with PVC beats.
    Step 3: The overall evidence points to PVC.

    ANSWER:
    LABEL: PVC
    CONFIDENCE: 86""",

    """TASK: Heartbeat anomaly detection (ECG)

    QUESTION:
    Classify the heartbeat as Normal or PVC.

    INPUT:
    Signal_summary: The signal appears steady and similar to typical ECG segments for normal beats.
    Features: mean=0.04, variance=0.02, fft_mean_magnitude=0.25
    Context: ECG sampled at 72Hz, window ~0.8s, lead=MLII

    REASONING:
    Step 1: Steady behavior suggests the beat is not anomalous.
    Step 2: Similarity to typical normal segments supports the normal label.
    Step 3: No abnormal morphology cues are noted.

    ANSWER:
    LABEL: Normal
    CONFIDENCE: 72""",

    """TASK: Heartbeat anomaly detection (ECG)

    QUESTION:
    Classify the heartbeat as Normal or PVC.

    INPUT:
    Signal_summary: The segment contains an irregular pattern and a noticeable morphology change within the beat window.
    Features: mean=0.05, variance=0.04, fft_mean_magnitude=0.33
    Context: ECG sampled at 72Hz, window ~0.8s, lead=MLII

    REASONING:
    Step 1: Irregular pattern suggests abnormal beat behavior.
    Step 2: Morphology change aligns with ventricular-origin abnormal beats.
    Step 3: This is more consistent with PVC than normal.

    ANSWER:
    LABEL: PVC
    CONFIDENCE: 79""",

    """TASK: Heartbeat anomaly detection (ECG)

    QUESTION:
    Classify the heartbeat as Normal or PVC.

    INPUT:
    Signal_summary: The waveform is regular, with no abrupt spikes or distortions noted.
    Features: mean=0.02, variance=0.01, fft_mean_magnitude=0.18
    Context: ECG sampled at 72Hz, window ~0.8s, lead=MLII

    REASONING:
    Step 1: No abrupt spikes implies stable morphology.
    Step 2: Regular pattern is characteristic of normal heartbeats.
    Step 3: Normal is the most likely label given the description.

    ANSWER:
    LABEL: Normal
    CONFIDENCE: 80""",

    """TASK: Heartbeat anomaly detection (ECG)

    QUESTION:
    Classify the heartbeat as Normal or PVC.

    INPUT:
    Signal_summary: The waveform is less regular and appears distorted compared to a typical normal beat.
    Features: mean=0.07, variance=0.05, fft_mean_magnitude=0.37
    Context: ECG sampled at 72Hz, window ~0.8s, lead=MLII

    REASONING:
    Step 1: Distortion and irregularity suggest abnormal morphology.
    Step 2: Increased variance supports the presence of abnormal fluctuations.
    Step 3: These cues are consistent with PVC.

    ANSWER:
    LABEL: PVC
    CONFIDENCE: 83""",

    """TASK: Heartbeat anomaly detection (ECG)

    QUESTION:
    Classify the heartbeat as Normal or PVC.

    INPUT:
    Signal_summary: The segment shows a stable pattern, and the beat shape does not appear abnormal.
    Features: mean=0.03, variance=0.02, fft_mean_magnitude=0.23
    Context: ECG sampled at 72Hz, window ~0.8s, lead=MLII

    REASONING:
    Step 1: Stability across the segment indicates typical behavior.
    Step 2: No abnormal shape cues suggests the beat is normal.
    Step 3: Normal is the most plausible label.

    ANSWER:
    LABEL: Normal
    CONFIDENCE: 71""",

    """TASK: Heartbeat anomaly detection (ECG)

    QUESTION:
    Classify the heartbeat as Normal or PVC.

    INPUT:
    Signal_summary: The signal includes an abnormal deviation and appears different from the expected normal morphology.
    Features: mean=0.06, variance=0.05, fft_mean_magnitude=0.39
    Context: ECG sampled at 72Hz, window ~0.8s, lead=MLII

    REASONING:
    Step 1: Abnormal deviation suggests an atypical beat within the window.
    Step 2: The morphology difference aligns with PVC-like characteristics.
    Step 3: The combination of cues supports PVC.

    ANSWER:
    LABEL: PVC
    CONFIDENCE: 84""",

    """TASK: Heartbeat anomaly detection (ECG)

    QUESTION:
    Classify the heartbeat as Normal or PVC.

    INPUT:n    Signal_summary: The waveform maintains consistent amplitude and regular structure throughout the window.
    Features: mean=0.04, variance=0.01, fft_mean_magnitude=0.21
    Context: ECG sampled at 72Hz, window ~0.8s, lead=MLII

    REASONING:
    Step 1: Consistent amplitude and low variance suggest stable morphology.
    Step 2: Regular structure aligns with normal heartbeat patterns.
    Step 3: No evidence supports an abnormal PVC morphology.

    ANSWER:
    LABEL: Normal
    CONFIDENCE: 79""",

    """TASK: Heartbeat anomaly detection (ECG)

    QUESTION:
    Classify the heartbeat as Normal or PVC.

    INPUT:
    Signal_summary: The beat window shows irregular fluctuations and a noticeably atypical waveform shape.
    Features: mean=0.05, variance=0.06, fft_mean_magnitude=0.41
    Context: ECG sampled at 72Hz, window ~0.8s, lead=MLII

    REASONING:
    Step 1: Irregular fluctuations raise variance and suggest abnormality.
    Step 2: Atypical waveform shape is consistent with PVC characteristics.
    Step 3: The evidence favors PVC over normal.

    ANSWER:
    LABEL: PVC
    CONFIDENCE: 86""",
]

for i, text in enumerate(Demos, start=1):
    filepath = f"/content/drive/MyDrive/AI Capstone (1)/Demos/Demo{i}.txt"
    with open(filepath, "w") as file:
        file.write(text)

doc_files = glob.glob("/content/drive/MyDrive/AI Capstone (1)/Docs/*.txt")
demo_files = glob.glob("/content/drive/MyDrive/AI Capstone (1)/Demos/*.txt")

all_files = []

for f in doc_files + demo_files:
    with open(f, "r") as file:
        all_files.append(file.read())


def chunk(file):
    if "TASK:" in file:
        return [file.strip()]
    examples = file.split(". ")
    return [" ".join(examples[i:i + 2]) for i in range(0, len(examples), 2)]


chunks = []
for t in all_files:
    chunks.extend(chunk(t))

model = SentenceTransformer("thenlper/gte-large")
embeddings = model.encode(chunks)

# BM25 index for hybrid retrieval
tokenized_chunks = [c.lower().split() for c in chunks]
bm25 = BM25Okapi(tokenized_chunks)

# BGE reranker
reranker = CrossEncoder("cross-encoder/ms-marco-MiniLM-L-6-v2")

print(df.head(1))
print(df.iloc[0]["signal_text"][:200])
print(chunks[:3])
print(embeddings.shape)

sample = df.sample(1).iloc[0]

# convert signal_text to float array
signal = np.array([float(x) for x in sample['signal_text'].split(", ")])

# plot ECG snippet
plt.figure(figsize=(10, 3))
plt.plot(signal)
plt.title(f"ECG Signal - Label: {sample['label']}")
plt.xlabel("Time (samples)")
plt.ylabel("Amplitude")
plt.grid(True)
plt.show()

# print features
print("Features:")
print(df[['label', 'mean', 'variance', 'fft_mean_magnitude']].head())


# Hybrid retrieval — combine BM25 + embedding scores
def hybrid_retrieve(query, top_k=TOP_K):
    query_embed = model.encode([query])
    cos_scores = cosine_similarity(query_embed, embeddings)[0]

    bm25_scores = np.array(bm25.get_scores(query.lower().split()))
    if bm25_scores.max() > 0:
        bm25_scores = bm25_scores / bm25_scores.max()

    combined = 0.5 * cos_scores + 0.5 * bm25_scores
    return np.argsort(combined)[::-1][:top_k].tolist()


# Rerank candidates with BGE
def rerank_chunks(query, candidate_indices, top_n=TOP_RERANK):
    pairs = [[query, chunks[i]] for i in candidate_indices]
    scores = reranker.predict(pairs)  # CrossEncoder uses .predict()
    ranked = sorted(zip(scores, candidate_indices), reverse=True)
    return [chunks[idx] for _, idx in ranked[:top_n]]


sample_text = sample['signal_text'][:200]
candidate_indices = hybrid_retrieve(sample_text)
retrieved_chunks = rerank_chunks(sample_text, candidate_indices)
retrieved_chunk = "\n\n---\n\n".join(retrieved_chunks)

print("\nMost relevant reasoning chunk:")
print(retrieved_chunk)

prompt = f""" You are a cardiologist analyzing ECG data.
TASK: Classify the heartbeat as Normal or PVC.

ECG SIGNAL: {sample['signal_text'][:300]}

FEATURES:
Mean: {sample['mean']}
Variance: {sample['variance']}
FFT Mean Magnitude: {sample['fft_mean_magnitude']}

RETRIEVED KNOWLEDGE: {retrieved_chunk}

Analyze the ECG and provide:
1. Step-by-step reasoning
2. Final label (LABEL: Normal or LABEL: PVC)
3. Confidence score (CONFIDENCE: 0-100)
"""

raw = ask_llm(prompt)
print(raw)

# Get label out of response
def parse_label(text):
    match = re.search(r'LABEL:\s*(Normal|PVC)', text, re.IGNORECASE)
    if match:
        return match.group(1)
    if re.search(r'\bPVC\b', text):
        return "PVC"
    if re.search(r'\bNormal\b', text, re.IGNORECASE):
        return "Normal"
    return "Unknown"


# Take 50 Normal beats and 50 PVC beats from dataset
eval_df = df.groupby("label").apply(
    lambda g: g.sample(50, random_state=42)
).reset_index(drop=True)

print(f"\nEvaluating {len(eval_df)} samples across 3 systems...")

# SYSTEM 1 PROMPT — Simple, just sends signals to the LLM
def make_baseline_prompt(row):
    return f"""You are a cardiologist analyzing ECG data.

    TASK: Classify the heartbeat as Normal or PVC.
    ECG SIGNAL: {row['signal_text'][:300]}
    FEATURES:
    Mean: {row['mean']}
    Variance: {row['variance']}
    FFT Mean Magnitude: {row['fft_mean_magnitude']}

    Respond with:
    LABEL: <Normal or PVC>
    CONFIDENCE: <0-100>
    """

# SYSTEM 2 PROMPT — Basic embedding retrieval only, No BGE
def make_rag_prompt(row, context):
    return f"""You are a cardiologist analyzing ECG data.
TASK: Classify the heartbeat as Normal or PVC.

ECG SIGNAL: {row['signal_text'][:300]}

FEATURES:
Mean: {row['mean']}
Variance: {row['variance']}
FFT Mean Magnitude: {row['fft_mean_magnitude']}

RETRIEVED KNOWLEDGE:
{context}

Respond with:
LABEL: <Normal or PVC>
CONFIDENCE: <0-100>
"""


# SYSTEM 3 PROMPT — Full pipeline with retrieved and reranked knowledge
# Best version: hybrid retrieval (BM25 + embeddings) + BGE reranker
def make_full_prompt(row, context):
    return f"""You are a cardiologist analyzing ECG data.
TASK: Classify the heartbeat as Normal or PVC.

ECG SIGNAL: {row['signal_text'][:300]}

FEATURES:
Mean: {row['mean']}
Variance: {row['variance']}
FFT Mean Magnitude: {row['fft_mean_magnitude']}

RETRIEVED KNOWLEDGE:
{context}

Analyze the ECG and provide:
1. Step-by-step reasoning
2. Final label (LABEL: Normal or LABEL: PVC)
3. Confidence score (CONFIDENCE: 0-100)
"""


# Simple embedding-only retrieval for System 2
# Simpler version of hybrid_retrieve(), no BM25, just embeddings.
# Used only for System 2

def simple_retrieve(query):
    # Turn the query into a vector
    query_vector = model.encode([query])

    # Score every chunk by how similar it is to the query
    scores = cosine_similarity(query_vector, embeddings)[0]

    # Return the top 2 chunk indices (highest scores first)
    top_indices = np.argsort(scores)[::-1][:TOP_RERANK]
    return top_indices.tolist()



# For each of the 100 samples
# 1. Build a prompt for each system
# 2. Send it to the LLM
# 3. Parse the label from the response
# 4. Check if it matches the ground truth


# This list will store one result per sample
comparison_results = []

for _, row in tqdm(eval_df.iterrows(), total=len(eval_df), desc="Evaluating"):

    # The query is just the first 200 characters of the signal text
    query = row['signal_text'][:200]

    # Baseline (no retrieval)
    # Send only the raw signal and features, no knowledge
    try:
        raw = ask_llm(make_baseline_prompt(row))
        pred_baseline = parse_label(raw)
    except Exception:
        pred_baseline = "Unknown"

    # RAG only (embedding retrieval, no reranker)
    # Retrieve the top 2 chunks using embeddings, add them to the prompt
    try:
        top_indices = simple_retrieve(query)
        context_rag = "\n\n---\n\n".join([chunks[i] for i in top_indices])

        raw = ask_llm(make_rag_prompt(row, context_rag))
        pred_rag = parse_label(raw)
    except Exception:
        pred_rag = "Unknown"

    # Full pipeline (hybrid retrieval + reranker)
    # Retrieve top 5 chunks with BM25 + embeddings, rerank to top 2
    try:
        candidate_indices = hybrid_retrieve(query)
        top_chunks = rerank_chunks(query, candidate_indices)
        context_full = "\n\n---\n\n".join(top_chunks)

        raw = ask_llm(make_full_prompt(row, context_full))
        pred_full = parse_label(raw)
    except Exception:
        pred_full = "Unknown"

    # Save the result for this sample
    comparison_results.append({
        "label": row["label"],  # ground truth
        "pred_baseline": pred_baseline,  # system 1 prediction
        "pred_rag": pred_rag,  # system 2 prediction
        "pred_full": pred_full,  # system 3 prediction
        "correct_baseline": pred_baseline == row["label"],
        "correct_rag": pred_rag == row["label"],
        "correct_full": pred_full == row["label"],
    })



comparison_df = pd.DataFrame(comparison_results)

print("\n========== BASELINE COMPARISON ==========")
print(f"{'System':<22} {'Overall':>8} {'Normal':>8} {'PVC':>8}")
print("-" * 50)

for col, name in [
    ("correct_baseline", "Baseline (no RAG)"),
    ("correct_rag", "RAG only"),
    ("correct_full", "Full pipeline"),
]:
    # Overall accuracy = fraction of correct predictions
    overall_accuracy = comparison_df[col].mean()

    # Per-class accuracy = how well it did on Normal vs PVC separately
    per_class = comparison_df.groupby("label")[col].mean()
    normal_acc = per_class.get("Normal", 0)
    pvc_acc = per_class.get("PVC", 0)

    print(f"{name:<22} {overall_accuracy:>7.1%} {normal_acc:>8.1%} {pvc_acc:>8.1%}")



# Save the full comparison (all 3 systems) — used by the dashboard
comparison_df.to_csv(
    "/content/drive/MyDrive/AI Capstone/baseline_comparison.csv",
    index=False
)

# Save just the full pipeline results separately
results_df = comparison_df[["label", "pred_full", "correct_full"]].copy()
results_df.columns = ["label", "predicted", "correct"]
results_df.to_csv(
    "/content/drive/MyDrive/AI Capstone/eval_results.csv",
    index=False
)

print("\nSaved: baseline_comparison.csv and eval_results.csv")

print('Overall Accuracies:')
print(f"Baseline (no RAG): {comparison_df['correct_baseline'].mean():.1%}")
print(f"RAG only: {comparison_df['correct_rag'].mean():.1%}")
print(f"Full pipeline: {comparison_df['correct_full'].mean():.1%}")

print('\nAccuracy per Class:')
print(comparison_df.groupby('label')[['correct_baseline', 'correct_rag', 'correct_full']].mean().applymap(lambda x: f'{x:.1%}'))

"""%cd "/content/drive/MyDrive/AI Capstone (1)"
!git init
!git config --global user.email ""
!git config --global user.name ""
!git add ai_capstone.py
!git add Docs/
!git add Demos/

